feat: If a PR has oss.gg and points assigned as labels, it should auto award on merge
formbricks/oss.gg pull request #102
Opened 2024-09-13 18:00 UTC by RajuGangitla

## What does this PR do?

If a PR has oss.gg and points assigned as labels, it should auto award on merge

Fixes #86 

https://github.com/user-attachments/assets/f3b692b0-6f64-4845-a436-313d2c99eb1b

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at oss.gg](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

2024-09-15 12:40 UTC, jobenjada requested changes

2024-09-15 12:40 UTC, jobenjada commented on lib/github/hooks/issue.ts
> +
let's first check if the PR itself has a points label and if so, award the points. If not, go and search in linked issues.

2024-09-15 12:40 UTC, jobenjada commented on lib/github/hooks/issue.ts
> +
make sure to not repeat the code for awarding points (and if the user isn't found creating one).

we already have that functionality in the /award function. You might have to move it to the utils.ts in the /github folder and then refactor both the onAwardPoints and your new function

2024-09-15 12:40 UTC, jobenjada commented on lib/github/hooks/issue.ts
> +        // Extract points from labels like "🕹️ 50 points", "🕹️ 100 points", etc.
we have a `extractPointsFromLabel` helper function in github/utils - please use this

2024-09-15 12:40 UTC, jobenjada commented on lib/github/hooks/issue.ts
> +          if (!user) {
as mentioned above, please create a helper function and refactor onAwardPoints to use it

2024-09-15 12:40 UTC, jobenjada commented on lib/github/hooks/issue.ts
> +          );
after the points are awarded, we want to add the same comment to the PR we issue on onAwardPoints. Here, also make sure to follow the DRY coding principle.

2024-09-17 05:52 UTC, RajuGangitla commented
@jobenjada pushed the latest changes

2024-09-17 09:35 UTC, jobenjada commented
code looks good, will test and merge likely on the weekend as I'm not sure if I have time before hand 🙌

2024-09-20 14:20 UTC, jobenjada approved these changes
LGTM

2024-09-20 14:20 UTC, merged

2024-09-20 14:20 UTC, jobenjada commented
/award 250